<?php

namespace App\Entity;

use App\Repository\InventorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

// This is our main user entity, and defines what records can be accessed in each session
// A lot of constraints and validation is autogenerated by Symfony's Maker bundle

// An Inventor's username and email must be unique

#[ORM\Entity(repositoryClass: InventorRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['Email'])]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this email')]
class Inventor implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    // This is checked by the application to see if the user is logged in,
    // and is referred to for access control in /config/packages/security.yaml
    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;
    
    // These name fields aren't currently implemented in the registration form
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $LastName = null;

    // In the future, this email will need to be validated so that account verification and date notifications can
    // be sent to the correct email address
    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    // This field is not currently implemented in the registration form
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PhoneNumber = null;

    // A user can have one type, a person type can have many users
    // This helps administrators know the types of users that use the system
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?PersonType $PersonType = null;

    // This is a collection of patents associated with the current user entity
    /**
     * @var Collection<int, Patent>
     */
    #[ORM\ManyToMany(targetEntity: Patent::class, mappedBy: 'Inventors')]
    private Collection $patents;

    public function __construct()
    {
        $this->patents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(?string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(?string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(?string $PhoneNumber): static
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getPersonType(): ?PersonType
    {
        return $this->PersonType;
    }

    public function setPersonType(?PersonType $PersonType): static
    {
        $this->PersonType = $PersonType;

        return $this;
    }

    /**
     * @return Collection<int, Patent>
     */
    public function getPatents(): Collection
    {
        return $this->patents;
    }

    public function addPatent(Patent $patent): static
    {
        if (!$this->patents->contains($patent)) {
            $this->patents->add($patent);
            $patent->addInventor($this);
        }

        return $this;
    }

    public function removePatent(Patent $patent): static
    {
        if ($this->patents->removeElement($patent)) {
            $patent->removeInventor($this);
        }

        return $this;
    }

}
