<?php

/*
This is the default PHP page that is autogenerated for the Symfony application.
See src/Controller/* for PHP page controllers, and templates/* for Twig templates.
*/

use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
